### ISSUE TITLE
Add Redirection to awards page when awards are opened on an index that does not exist!

### ISSUE THREAD

**Issue by SamakshAgarwal1112** [BitByte-TPC/alumni#145]
## Is your feature request related to a problem? Please describe.
Whenever user tries to open an `/awards/` page on an index that does not exist, for example if user tries to open `/awards/2/` here, but no award is there to be displayed at index 2, the page shows a DoesNotExist error like this.

![Screenshot from 2024-06-01 13-00-29](https://github.com/BitByte-TPC/alumni/assets/129520330/058b2029-e97b-4241-81d4-c9cc30155e56)

## Describe the solution you'd like!
Whenever user opens the awards page on a non-existent index, the user should be simply redirected to the `/awards/` page.

## Describe alternatives you've considered
None

## Developer Help
None

**Comment by LunarShadow152004** [comment]
Hi Sir
![Screenshot 2024-06-01 210358](https://github.com/BitByte-TPC/alumni/assets/163876039/bc2354eb-2097-4b40-b7fc-2bb482f40645)
,
I'm interested in this issue. I would use an `if` and `else` statement to check if the `id` is present or not by using `Award.objects.filter(award_id=id).exists()`.
If it does not exist, then I will render the awards page.

Here is code
def award(request, id):
    if Award.objects.filter(award_id=id).exists():
        award = Award.objects.get(award_id=id)
        return render(request, "awards/award.html", {"award": award})
    else:
        return render(request, "awards/award.html")

**Comment by SamakshAgarwal1112** [comment]
@LunarShadow152004  The approach is good but I would suggest using a try and except technique.

**Comment by LunarShadow152004** [comment]
@SamakshAgarwal1112 
OK sir,
I have applied try and except method

**Here is the code :  ** 
`    try:
        award = Award.objects.get(award_id=id)
        return render(request, "awards/award.html", {"award": award})
    except:
        return render(request, "awards/award.html")`

**Comment by SamakshAgarwal1112** [comment]
@LunarShadow152004 
Also, one more thing!
On Github, You don't have to address the maintainer as "sir". Simply tag them or use their first name.
