### ISSUE TITLE
Add a default `/awards/` page.

### ISSUE THREAD

**Issue by SamakshAgarwal1112** [BitByte-TPC/alumni#146]
## Is your feature request related to a problem? Please describe.
The `/awards/` page is currently an empty page with just a "Lets get started!" text in it. 

## Describe the solution you'd like!
Make a `/awards/` page following the standard convention, i.e a header with title awards, a footer and a dialog box floating in between header and footer, with a "(N) awards to display!", N being the number of awards. Additionally make sure the page is responsive.

## Describe alternatives you've considered
None

## Developer Help
None

**Comment by ritankarsaha** [comment]
**@SamakshAgarwal1112**  **I would like to work on this issue.** 

### Explanation:-
The html template file awards/award.html is already listed in the view.py file. 
**So i would like to modify the index.html file in the awards folder of the templates folder from "Lets get started!" to do the above tasks efficiently - a header with title awards, a footer and a dialog box floating in between header and footer, with a "No awards to display!". Additionally i would also make sure its responsive.**

**Please assign me this issue under BSoC'24. @SamakshAgarwal1112**  Thank You.

**Comment by SamakshAgarwal1112** [comment]
@ritankarsaha Actually the text to be displayed has been updated from "No awards to display" to "(N) awards to display", N being the total number of awards.

**Comment by ritankarsaha** [comment]
> @ritankarsaha Actually the text to be displayed has been updated from "No awards to display" to "(N) awards to display", N being the total number of awards.

**@SamakshAgarwal1112 Okaay sir, will do the necessary changes to (N) awards to display, n being the total no.of awards by. modifying the views.py as well to return the count of total awards listed.**

**Could you please assign me this issue?**

**Comment by ritankarsaha** [comment]
I have fixed this issue #146 (Add a default /awards/ page.) and also opened a pull request for the same #148.

Thank You.

**Comment by ritankarsaha** [comment]
@SamakshAgarwal1112 i have made the necessary changes as asked in the last comment.
Thank You.

**Comment by ritankarsaha** [comment]
@SamakshAgarwal1112  I have made the necessary changes - fixing the icon with text error and updating the title as asked in the last comment and pushed my commits into the PR.
Thank You.
