### ISSUE TITLE
Add default text for event entries not specified

### ISSUE THREAD

**Issue by SamakshAgarwal1112** [BitByte-TPC/alumni#150]
## Is your feature request related to a problem? Please describe.
At The `/events/` page, whenever an event is listed that doesn't contain the optional fields, "Location" or "Organiser", then it displays the event with a lot of empty space like in the image shown below:

![Screenshot 2024-06-05 024125](https://github.com/BitByte-TPC/alumni/assets/129520330/bfa5e7e9-3268-440e-bb5a-8c6a5e5948c4)

## Describe the solution you'd like!
Display the text "N/A" in place of these fields whenever these fields are empty.

## Describe alternatives you've considered
Feel free to suggest!

## Developer Help
To create an event, you can either create one from your django-admin at `/admin/events_news/event/` or you can create one at `/adminportal/events`. Then you can view it at `/events/`.

**Comment by sarthakChauhan12** [comment]
Can I work on this issue?

**Comment by NightFury742** [comment]
Sure @sarthakChauhan12 !

**Comment by NightFury742** [comment]
I see you have left comments on other issues as well. It's highly appreciated if you finish this one first before getting more assigned.

**Comment by ritankarsaha** [comment]
I would like to work on this issue. Th approach would be to be use django's template language to check for empty fields and provide a default message "NA" when these fields are empty, updating the HTML template events.html when the evernts are being displayed

@NightFury742  Could you pls assign me this issue? 
Thank You.

**Comment by NightFury742** [comment]
Go ahead @ritankarsaha !

**Comment by ritankarsaha** [comment]
@NightFury742 @SamakshAgarwal1112 I have fixed the issue #150 and pushed a PR #154 for the same
