### ISSUE TITLE
Dsiplay state information in Profile card for member search results.

### ISSUE THREAD

**Issue by NightFury742** [BitByte-TPC/alumni#151]
## Is your feature request related to a problem? Please describe.
When members are filtered based on citites, currently all the profiles of the matching city shows up. However, the state where the member resides is not included in the profile card. This causes discrepencies especially when there exists two cities having the same name but are in different states.

![Screenshot from 2024-06-05 02-45-07](https://github.com/BitByte-TPC/alumni/assets/119070798/f56d830e-1baf-41ba-a8c0-bed9bf94f6c2)

When clicked on each card
| In UP | In HP|
|---|---|
| ![Screenshot from 2024-06-05 02-45-16](https://github.com/BitByte-TPC/alumni/assets/119070798/8ad20d63-af3e-46e2-8702-027b192a9a62) | ![Screenshot from 2024-06-05 02-45-22](https://github.com/BitByte-TPC/alumni/assets/119070798/77067445-2326-494f-8136-bfbddc9e2596) |

## Describe the solution you'd like!
Display the state field in the profile card next to city.

## Describe alternatives you've considered
None

## Developer Help
Populate the DB by adding temporary data to `data_acc.xlsx` under `/scripts` and then running `python manage.py populate`. Add two cities having the same name which are in different state to reproduce this.

**Comment by sarthakChauhan12** [comment]
I'd like to work on this issue. Can I help?

**Comment by LunarShadow152004** [comment]
Hello,
I'd like to work on this issue.

**Comment by NightFury742** [comment]
Sure @LunarShadow152004 !
