### ISSUE TITLE
Make and implement a custom 404 Error page

### ISSUE THREAD

**Issue by NightFury742** [BitByte-TPC/alumni#152]
## Is your feature request related to a problem? Please describe.
Create a custom 404 error page.

## Describe the solution you'd like!
As of now the website uses the default error page by django. Create a template for 404 error page as such and implement it so that a user is redirected to it whenever a 404 error occurs.

## Describe alternatives you've considered
Feel free to revamp the design if you have better ideas.

## Developer Help
**New design:**
![Group 14](https://github.com/BitByte-TPC/alumni/assets/119070798/b044b340-f0f3-42ba-ad2d-fce7a31ea991)

**Comment by sarthakChauhan12** [comment]
Can I work on this issue?

**Comment by Vaibhavsahu2810** [comment]
@NightFury742 I would like to work on this issue. The approach to will be easy to first create a 404.html file in templates then in settings i will setup debug = false to use my error template

**Comment by Vaibhavsahu2810** [comment]
<img width="1470" alt="Screenshot 2024-06-07 at 11 48 13 AM" src="https://github.com/BitByte-TPC/alumni/assets/154520239/fe3e59cb-c259-45c6-98b8-2bb5b6afe543">
can i do this , earlier it was looking very boring and old 
![image](https://github.com/BitByte-TPC/alumni/assets/154520239/e3acbc39-1ea4-4253-b5cb-8548553c89da)
@NightFury742 what's your thoughts about this

**Comment by NightFury742** [comment]
@Vaibhavsahu2810 The page looks good! However we intend to keep the look of this website professional. So if you come up with a more professional and simple desgin it would be much appriciated or else you could use the provided design

**Comment by Vaibhavsahu2810** [comment]
@NightFury742 @SamakshAgarwal1112 have completed the issue #152 and linked a PR for the same #156
