### ISSUE TITLE
[DOCUMENTATION] Update readme to install different version of python

### ISSUE THREAD

**Issue by NightFury742** [BitByte-TPC/alumni#153]
## Is your feature request related to a problem? Please describe.
Document additional steps to install **Python3.9** and use it while creating a virtual env,

## Describe the solution you'd like!
As of know, the incompatibility with the latest Python versions is creating various module version related issues when setting up the project. We need to document additional steps to install **Python3.9** and use it while creating a virtual env,

## Describe alternatives you've considered
None

## Developer Help
Checkout Pyenv

**Comment by sarthakyeole** [comment]
@NightFury742  Yes, my feature request is related to the problem.
I will solve the issue with the help of ‘pyenv’ such that the user can use the 3.9 version of Python for the project in a virtual environment while using the latest version of Python globally.

**Comment by SamakshAgarwal1112** [comment]
@sarthakyeole Go Ahead!
