### ISSUE TITLE
[FEATURE] Implement functionality for Blogs

### ISSUE THREAD

**Issue by SamakshAgarwal1112** [BitByte-TPC/alumni#158]
## Is your feature request related to a problem? Please describe.
The blog feature is to be implemented on the website. The entire idea is as follows:-
Every now and then, there will be campaigns running on the website revolving around some theme. Now the alumni will have a feature to write blogs on the website. The alumni will have a choice to dedicate the blog to the campaign running at that time on the website or not. After the blog is published, people can read them and also leave comments.

## Describe the solution you'd like!
Now, you are required to implement the models, views, and URLs for the feature. For your ease, the models for the blogs are already implemented in the `feature/blog` branch in the upstream repository. Feel free to reuse those. Accordingly, views are to be defined for CRUD operation of blogs, filtering of blogs, CRUD operation of campaigns, and CRUD operation of replies.

## Describe alternatives you've considered
Feel free to suggest!

## Developer Help
Reuse models in `feature/blog` branch that will give you to better understanding of the data structure of blogs. Also, for reference, could see `events` and `job_postings`!

**Comment by rohansen856** [comment]
@SamakshAgarwal1112 i would like to work on this issue. i would create the necessary html file to be used  in the templates section. in `Views.py` i would create the view module to successfully render the html file there and display a formatted output. Also in `Urls.py` i will define a custom URL so that i can effectively redirect a website to it. Finally i would run python manage.py make migrations. i would adhere to the `feature/blog` for any help with the schema.

**Comment by SamakshAgarwal1112** [comment]
@rohansen856 Your PR in Busify is under review right now and changes have been requested. First, get it completely approved before asking for another issue.

**Comment by LunarShadow152004** [comment]
@SamakshAgarwal1112 I would like work on this issue

**Comment by SamakshAgarwal1112** [comment]
@LunarShadow152004 Go ahead. You only need to work on the views and URLs for now. We'll see about the HTML templates later.

**Comment by SamakshAgarwal1112** [comment]
@LunarShadow152004 What's the issue status?

**Comment by LunarShadow152004** [comment]
@SamakshAgarwal1112  I have completed  CRUD operation of blogs and CRUD operation of campaigns
