### ISSUE TITLE
[FEATURE] Make a detailed blog page.

### ISSUE THREAD

**Issue by SamakshAgarwal1112** [BitByte-TPC/alumni#163]
## Is your feature request related to a problem? Please describe.
The detailed blog page is to be created at `\blogs\<id-of-that-blog>\`.

## Describe the solution you'd like!
Make a `\blogs\<id-of-that-blog>\` page following the standard convention, i.e a header, a footer, and a box with all details in it. Additionally, make sure the page is responsive.

## Describe alternatives you've considered
Feel free to suggest!

## Developer Help
For reference, you can check out detailed pages of news at `\news\<id>` or profiles at `profile\<id>`.

**Comment by sarthakyeole** [comment]
@SamakshAgarwal1112 I would like to work on this issue.
I will do this with the help of HTML templates and to make this page responsive I will use CSS.

**Comment by SamakshAgarwal1112** [comment]
@sarthakyeole Sure. Please go ahead.

**Comment by SamakshAgarwal1112** [comment]
@sarthakyeole Update on the issue?

**Comment by sarthakyeole** [comment]
@SamakshAgarwal1112 Yes, will complete soon

**Comment by SamakshAgarwal1112** [comment]
@sarthakyeole You just had to create the `blog.html` page. There is no need for other changes. Please remove them and resolve conflicts. Also, the new views for blogs have been created now so, do remember to change the redirection to your `blog.html` instead of `blog_detail.html`. Do refactor your logic according to those views as currently it is not showing the blog details.

**Comment by SamakshAgarwal1112** [comment]
@sarthakyeole How are the updates going? Feel free to reach out to me in case any help is required.

**Comment by sarthakyeole** [comment]
@SamakshAgarwal1112  Yes, I will complete it soon.
