### ISSUE TITLE
[BUG] DoesNotExist Error at News and Chapter

### ISSUE THREAD

**Issue by SamakshAgarwal1112** [BitByte-TPC/alumni#164]
## Is your feature request related to a problem? Please describe.
Whenever user tries to open a `/news/` page or a `/chapter/` page on an index that does not exist, for example if user tries to open `/news/9/` or `/chapter/5/`, but no data is there to be displayed at that index, the page shows a DoesNotExist error like this.

![Screenshot 2024-06-27 040838](https://github.com/BitByte-TPC/alumni/assets/129520330/81815bac-d59a-4180-8133-648f02f05b20)

## Describe the solution you'd like!
Whenever user opens the page on a non-existent index, the user should be simply redirected to the `/news/` or `/chapter/` page respectively.

## Describe alternatives you've considered
None.

## Developer Help
None.

**Comment by SamakshAgarwal1112** [comment]
@ritankarsaha Since this is a good first issue, please let other people who haven't contributed yet or have just started contributing, take it.

**Comment by yashpatil641** [comment]
@SamakshAgarwal1112 I would like work on this issue

**Comment by SamakshAgarwal1112** [comment]
@yashpatil641 Go ahead.
